---
title: "Ecomgraphs"
author: "Asmer Asrar Safi"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(ggridges)

```

```{r}
# Use Data_Benchmark or Data_Benchmark_2018 for all 
# The dataset is provided in the gapminder library

library(gapminder)
data <- Data_Benchmark_2018 %>% filter(Year=="2018") %>% dplyr::select(-Year)
data$pop
# Bubble Plot 
data %>%
  arrange(desc(dispi)) %>%
  mutate(Country = factor(Country, Country)) %>%
  ggplot(aes(x=smart, y=ecom_mbl, size=dispi, color=Country)) +
  geom_point(alpha=0.5) +
  scale_size(range = c(.1, 24), name="Disposable Income") +
  theme_light() +
  labs(x = "Possession of Smartphone",
       y = "Mobile E-Commerce Retail Value (% total retail value)",
       title = "Mobile E-Commerce Retail Value and Smartphone Posession in Benchmark Countries",
       subtitle = "Source: Digital Intelligence Index Report 2019",
       caption = "Data: Euromonitor") +
  theme(axis.title.x = element_text(size = 8), 
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
  theme(legend.position = "bottom")

```

```{r}
# Grouped Scatter 
ggplot(data = Data_Benchmark,
       mapping = aes(x = smart , 
                     y = ecom_mbl,
                     color = Country)) +
  geom_point(alpha = .7,
             size = 3) +
  geom_smooth(method = "lm", 
              se = FALSE, 
              size = 1.5) +
   theme_light() +
  labs(x = "Possession of Smartphone",
       y = "Mobile E-Commerce Retail Value (% total retail value)",
       title = "Mobile E-Commerce Retail Value and Smartphone Posession in Benchmark Countries",
       subtitle = "Source: Digital Intelligence Index Report 2019",
       caption = "Data: Euromonitor") +
  theme(axis.title.x = element_text(size = 8), 
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) 
```

```{r}
# Density - 
ggplot(Data_Pak, aes(x = ecom_mbl)) +
  geom_density(fill = "skyblue", 
               ) +
  theme_light() +
  labs(x = "Mobile E-Commerce Retail Value (% total retail value)",
       y = "Density",
       title = "Ecommerce Mobile Acitivity Density",
       subtitle = "Bandwidth = 1",
       caption = "Data: Euromonitor") +
  theme(axis.title.x = element_text(size = 8), 
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8))
  
```

```{r}
# Scatter with Loess Smooth Line 

paki <- Data_2018 %>% 
  filter(Country == "PAK") %>% 
  select(dispi, ecom_mbl)


ggplot(Data_2018,
       aes(x = dispi,
           y = ecom_mbl)) +
  geom_point(color = "steelblue") +
  geom_smooth(color = "tomato") +
    geom_point(data = paki,
             aes(dispi, ecom_mbl),
             shape = 21, 
             fill = 'tomato',
             color = 'black') +
  geom_label_repel(data = paki,
                  aes(dispi, ecom_mbl, label = "PAK"),
                  box.padding   = 0.1,
                  point.padding = 0.1,
                  segment.color = 'red',
                  color = 'black') +
  labs(x = "Disposable Income per capita",
       y = "Mobile E-Commerce Retail Value (% total retail value)",
       title = "Mobile E-Commerce Retail value vs Disposable Income",
       subtitle = "All Countries",
       caption = 'Data Source: Euromonitor') +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8))



```

```{r}
#Line Graph - Univariate
ggplot(Data_Pak, 
       aes(x = Year, 
           y = ecom_mbl)) +
  geom_line(size = 1.5, 
            color = "lightgrey") +
  geom_point(size = 3, 
             color = "steelblue") +
  labs(y = "Mobile E-commerce Retail Value (% total retail value)", 
       x = "Year",
       title = "Mobile E-commerce Retail Value Over Time",
       subtitle = "Pakistan (2008-2019)",
       caption = 'Data Source: Euromonitor') +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
  scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2019)) 


```

```{r}
#Density 
ggplot(Data_Benchmark, 
       aes(x = dispi, 
           fill = Country)) +
  geom_density(alpha = 0.4) +
  labs(title = "Mobile E-commerce Retail by Rank",
       y = "Density",
       x = "Disposable Income per capita",
       subtitle = "Benchmark Countries",
       caption = "Data: Euromonitor")  +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) 



```

```{r}
#Ridgeline Graphs
# create ridgeline graph

ggplot(Data_Benchmark, 
       aes(x = ecom_mbl, 
           y = Country, 
           fill = Country)) +
  geom_density_ridges() + 
  theme_ridges() +
  labs(title = "Mobile E-Commerce Retail Value by Country", 
       y = "Country",
       x = "Mobile E-Commerce Retail Value (% total retail value)",
       caption = "Data Source: Euromonitor") +
  theme(legend.position = "none") +
    theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) 


```

```{r}
#Fancy Chart 
ggplot(Data_Benchmark_2018, 
       aes(x=dispi, 
           y=reorder(Country, dispi))) +
  geom_point(color="blue", 
             size = 2) +
  geom_segment(aes(x = 40, 
                   xend = dispi, 
                   y = reorder(Country, dispi), 
                   yend = reorder(Country, dispi)),
               color = "lightgrey") +
  labs (x = "Disposable Income per capita",
        y = "Country",
        title = "Disposable Income per capita Over Time",
        subtitle = "Benchmark Countries: 2018",
        capion = "Source: Euromonitor") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) + 
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8))
  
```

```{r}
#Multivariate Graphs 
# plot life expectancy by year, for each country
ggplot(Data_Benchmark, aes(x=Year, y = ecom_mbl)) +
  geom_line(color="grey") +
  geom_point(color="blue") +
  facet_wrap(~Country) + 
  theme_minimal(base_size = 9) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = "Mobile E-commerce Retail Value (% total retail value)", 
       x = "Year",
       title = "Changes in Mobile E-commerce Retail Value Over Time",
       subtitle = "Benchmark Countries (2008-2019)",
       caption = 'Data Source: Euromonitor') +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
  scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2019)) 

```

```{r}
#Scatter - Another One 
ggplot(Data_Benchmark, 
       aes(x = dispi, 
           y = ecom_mbl, 
           color = Country, 
           size = smart)) +
  geom_point(alpha = .6) +
  labs(title = "Mobile E-Commerce Retail Value, Disposable Income, and Smartphone Peneteration",
       subtitle = "Benchmark Countries: 2018",
       caption = "Data Source: Euromonitor", 
       y = "Mobile E-Commerce Retail Value (% total retail value)",
       x = "Disposable Income per capita",
       size = "Posession of Smartphone") +
   theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) 
```

```{r}
#Scatter Another One 
ggplot(Data_Benchmark,
       aes(x = dispi,
           y = ecom_mbl,
           color = Country)) +
  geom_point(alpha = .4,
             size = 3) +
  geom_smooth(se=FALSE,
              method = "lm",
              formula = y~poly(x,2),
              size = 1.5) +
  labs(x = "Disposable Income per capita",
       title = "Mobile E-Commerce Retail Value by Disposable Income and Country",
       y = "Mobile E-Commerce Retail Value (% of total retail value)",
       color = "Country", 
       subtitle = "Benchmark Countries: 2018", 
       caption = "Data Source: Euromonitor") +
  scale_color_brewer(palette = "Set1") +
  theme_minimal() +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) 

```

```{r}
#Area Chart
# stacked area chart
data(Data_Benchmark, package = "gcookbook")
ggplot(Data_Benchmark, aes(x = Year,
                     y = ecom_mbl,
                     fill = Country)) +
  geom_area(color = "black") +
  labs(title = "Mobile E-Commerce Retail Value by Country",
       x = "Year",
       y = "Mobile E-Commerce Retail Value (% of total retail value)", 
       caption = "Data Source: Euromonitor",
       subtitle = "Benchmark Countries: 2008-2018") +
  scale_x_continuous(breaks = c(2008, 2010, 2012, 2014, 2016, 2018)) + 
  theme_light() +
   theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5),
        legend.title = element_text(size = 10))

  




```


```{r}

#Stacked Chart - Another one
data(Data_Benchmark, package = "gcookbook")
ggplot(Data_Benchmark, aes(x = Year,
                     y = ecom_mbl,
                     fill = forcats::fct_rev(Country))) +
  geom_area(color = "black") +
  labs(title = "Mobile E-Commerce Retail Value by Year and Age Group",
       subtitle = "Benchmark Countries: 2008 to 2018",
       caption = "Data Source: Euromonitor",
       x = "Year",
       y = "Mobile E-Commerce Retail Value (% of total retail value)",
       fill = "Age Group") +
  scale_fill_brewer(palette = "Set2") +
  scale_x_continuous(breaks = c(2008, 2010, 2012, 2014, 2016, 2018)) +
  theme_minimal() +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5),
        legend.title = element_text(size = 8)) 
  
```
```{r}
#Time Series
df <- Data_Benchmark %>%
  filter(Year %in% c(2008, 2012, 2015, 2018) &
           Country %in% c("BGD", "PAK",
                          "NGA", "VNM",
                          "TUR", "EGY",
                          "IND")) %>%
  mutate(Year = factor(Year),
         ecom_mbl = round(ecom_mbl))

# create slope graph
newggslopegraph(df, Year, ecom_mbl, Country) +
  labs(title="Life Expectancy by Country",
       subtitle="Central America",
       caption="source: gapminder")

```


