---
title: "Spider"
author: "Asmer Asrar Safi"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(ggrepel)
library(ggthemes)
library(viridis)
library(fmsb)
library(ggridges)
library(skimr)
library(tidyverse)
```

```{r}

# Instructions: 1) Top 5 variables + Ecommerce yearly line graphs of Pakistan and Pakistan with comparator countries. 2) Use of Digital Money graphs (from picture sent) for just Pakistan (cluster them together if you can, but make individual ones too.)


# Filtering for all comparator countries from 2008 - 2019

comp_years <- Uzair_Data_Merged %>% 
  filter(Country %in% c("IND", 
                        "BGD",
                        "TUR",
                        "VNM", 
                        "NPL", 
                        "ZMB",
                        "PAK",
                        "KEN", 
                        "CHN", 
                        "MAR", 
                        "LAO"))

# Filtering for Pakistan (2008 - 2019)
pak_years <- Uzair_Data_Merged %>% 
  filter(Country == "PAK")

```


```{r}

# Facet Wrap graphs for Ecom/Top 5 variables

facet_years <- ggplot(comp_years, aes(x=Year, y = smart, color = Country)) +
  geom_line(color="grey") +
  geom_point(color="blue") + 
  facet_wrap(~Country) + 
  theme_minimal(base_size = 9) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = "Smartphone Possession", 
       x = "Year",
       title = "Changes in Smartphone Possession Over Time",
       subtitle = "Benchmark Countries (2008-2019)") +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
    scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2019)) 

facet_years

```

```{r}

ggplot(comp_years, aes(x=Year, y = smart, color = Country)) +
  geom_point(aes(Year, smart), color = "grey70", shape = 21, fill = "grey70") + 
  geom_line(aes(Year, smart)) +
  theme_minimal(base_size = 9) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = "Smartphone Possession", 
       x = "Year",
       title = "Changes in Smartphone Possession Over Time",
       subtitle = "Benchmark Countries (2008-2019)") +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
    scale_x_continuous(breaks = c(2007, 2010, 2013, 2016, 2019)) 




```

```{r}
# Pak Digital Uptake graphs
ggplot(pak_years, aes(x=Year, y = ictinv, color = Country)) +
  geom_line(color="grey") +
  geom_point(color="darkgreen") + 
  theme_minimal(base_size = 9) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = " Capital Investment in ICT", 
       x = "Year",
       title = "Changes in Capital Investment in ICT Over Time",
       subtitle = "Pakistan (2008-2018) - Use of Digital Money") +
  theme_light() +
  theme(axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(face = "bold",
                                    size = 10,
                                    hjust = 0.5),
        plot.subtitle = element_text(size = 10,
                                     hjust = 0.5),
        plot.caption =  element_text(face = "italic",
                                      hjust = 0.5,
                                      size = 8)) +
    scale_x_continuous(breaks = c(2007:2019)) 


```





